name: Javascript Format Commit

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  format_commit:
    runs-on: ubuntu-latest
    container: node:12.18.4

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initialize Yarn
        run: yarn

      - name: Format JavaScript Code
        run: yarn format:write

      - name: Commit and Push Formatting Changes
        run: |
          git config --global --add safe.directory $(realpath .)
          git config user.email "andrew@jarombek.com"
          git config user.name "Andrew Jarombek"
          git add .
          
          if [[ -n $(git status -s) ]]; then
            git commit -m "Format Code with Prettier"
            git push
            echo "Changes committed and pushed to the remote repository."
          else
            echo "No local changes to commit and push."
          fi
